# Generated by Django 3.2.7 on 2021-09-12 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cnickname', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('cfirstname', models.CharField(max_length=45)),
                ('clastname', models.CharField(max_length=45)),
                ('dbirthdate', models.DateField()),
                ('cmail', models.CharField(max_length=255)),
                ('cavatar', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cphone', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('clongitude', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('clatitude', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('cdescription', models.TextField(blank=True, default=None, null=True)),
                ('cipUser', models.CharField(blank=True, default=None, max_length=45, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=45)),
                ('cicon', models.CharField(max_length=100)),
                ('tdescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='characteristic_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnameCountry', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=45)),
                ('cabbreviation', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buser1Like', models.BooleanField(default=False)),
                ('buser2Like', models.BooleanField(default=False)),
                ('bmatch', models.BooleanField(default=False)),
                ('nidUser1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('nidUser2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidMatch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.match')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmessage', models.TextField()),
                ('ddate', models.DateTimeField()),
                ('nidRoom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.room')),
                ('nidUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=45)),
                ('drelaseDate', models.DateField()),
                ('cimage', models.CharField(max_length=100)),
                ('nidCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.category')),
            ],
        ),
        migrations.CreateModel(
            name='detail_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidCharacteristic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.characteristic_user')),
                ('nidUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detail_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidGame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.game')),
                ('nidUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detail_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.category')),
                ('nidUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnameCity', models.CharField(max_length=45)),
                ('nidCountry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.country')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='nidCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='nidGender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.gender'),
        ),
    ]
