# Generated by Django 3.2.7 on 2021-09-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cnameCity',
            field=models.CharField(max_length=255),
        ),
    ]
